default_language_version:
  python: python3.7
default_install_hook_types: [commit-msg]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
